package toolreg

import (
	"fmt"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/alextebbs/lore/internal/richtext"
	"github.com/alextebbs/lore/internal/tools"
)

// TS type generation (ADR 0016 follow-through): the wire shapes the
// frontend consumes are generated from the Go structs that produce
// them. cmd/gentools writes web/src/api-types.gen.ts; a test compares
// the file against RenderTSTypes so shape drift fails CI.

var tsRoots = []any{
	tools.World{}, tools.WorldSettings{}, tools.EntryType{},
	tools.FieldDef{}, tools.RelationConfig{}, tools.EntrySummary{},
	tools.Entry{}, tools.FieldValue{}, tools.RelationSection{},
	tools.Edge{}, tools.EntryRef{}, tools.Revision{},
	tools.RevisionDetail{}, tools.Graph{}, tools.GraphNode{},
	tools.GraphEdge{}, tools.SearchResult{}, tools.Tray{},
	tools.TrayItem{}, tools.CanonScope{}, tools.WorldDump{},
	tools.TypeDump{}, tools.EntryDump{}, tools.EdgeDump{},
	tools.VaultFile{}, tools.VaultImportResult{}, tools.EntryRow{},
}

var (
	docNodeT = reflect.TypeOf(richtext.Node{})
	docMarkT = reflect.TypeOf(richtext.Mark{})
	timeT    = reflect.TypeOf(time.Time{})
)

func RenderTSTypes() string {
	emitted := map[string]string{}
	order := []string{}
	var emit func(t reflect.Type)

	tsType := func(t reflect.Type) string { return "" } // forward decl
	var tsOf func(t reflect.Type) string
	tsOf = func(t reflect.Type) string {
		switch t {
		case docNodeT:
			return "DocNode"
		case docMarkT:
			return "DocMark"
		case timeT:
			return "string"
		}
		switch t.Kind() {
		case reflect.String:
			return "string"
		case reflect.Bool:
			return "boolean"
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32,
			reflect.Int64, reflect.Uint, reflect.Uint8, reflect.Uint16,
			reflect.Uint32, reflect.Uint64, reflect.Float32, reflect.Float64:
			return "number"
		case reflect.Interface:
			return "unknown"
		case reflect.Pointer:
			return tsOf(t.Elem())
		case reflect.Slice:
			if t.Elem().Kind() == reflect.Uint8 { // json.RawMessage
				return "unknown"
			}
			return tsOf(t.Elem()) + "[] | null"
		case reflect.Map:
			return fmt.Sprintf("Record<string, %s>", tsOf(t.Elem()))
		case reflect.Struct:
			emit(t)
			return t.Name()
		}
		return "unknown"
	}
	_ = tsType

	emit = func(t reflect.Type) {
		if t == docNodeT || t == docMarkT || t == timeT {
			return
		}
		if _, done := emitted[t.Name()]; done {
			return
		}
		emitted[t.Name()] = "" // reserve against recursion
		var b strings.Builder
		fmt.Fprintf(&b, "export interface %s {\n", t.Name())
		var walkFields func(rt reflect.Type)
		walkFields = func(rt reflect.Type) {
			for i := 0; i < rt.NumField(); i++ {
				f := rt.Field(i)
				if f.Anonymous {
					walkFields(f.Type)
					continue
				}
				tag := f.Tag.Get("json")
				if tag == "-" || tag == "" {
					continue
				}
				parts := strings.Split(tag, ",")
				name := parts[0]
				optional := ""
				if len(parts) > 1 && strings.Contains(tag, "omitempty") {
					optional = "?"
				}
				fmt.Fprintf(&b, "  %s%s: %s;\n", name, optional, tsOf(f.Type))
			}
		}
		walkFields(t)
		b.WriteString("}\n")
		emitted[t.Name()] = b.String()
		order = append(order, t.Name())
	}

	for _, root := range tsRoots {
		emit(reflect.TypeOf(root))
	}
	sort.Strings(order)

	var out strings.Builder
	out.WriteString("// GENERATED by cmd/gentools from internal/tools structs — do not edit.\n")
	out.WriteString("// Regenerate: make tools-docs\n")
	out.WriteString(`import type { DocMark, DocNode } from "./doc";` + "\n")
	out.WriteString("export type { DocMark, DocNode };\n\n")
	for _, name := range order {
		out.WriteString(emitted[name])
		out.WriteString("\n")
	}
	return out.String()
}
