// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, world_id, user_id, title)
VALUES ($1, $2, $3, $4)
RETURNING id, world_id, user_id, title, evicted, created_at
`

type CreateConversationParams struct {
	ID      pgtype.UUID
	WorldID pgtype.UUID
	UserID  pgtype.UUID
	Title   string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.WorldID,
		arg.UserID,
		arg.Title,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.UserID,
		&i.Title,
		&i.Evicted,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, conversation_id, role, content)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, role, content, created_at
`

type CreateMessageParams struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Content        []byte
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createPin = `-- name: CreatePin :exec
INSERT INTO context_pins (user_id, world_id, entry_id, with_neighbors)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, world_id, entry_id)
DO UPDATE SET with_neighbors = EXCLUDED.with_neighbors
`

type CreatePinParams struct {
	UserID        pgtype.UUID
	WorldID       pgtype.UUID
	EntryID       pgtype.UUID
	WithNeighbors bool
}

func (q *Queries) CreatePin(ctx context.Context, arg CreatePinParams) error {
	_, err := q.db.Exec(ctx, createPin,
		arg.UserID,
		arg.WorldID,
		arg.EntryID,
		arg.WithNeighbors,
	)
	return err
}

const deletePin = `-- name: DeletePin :exec
DELETE FROM context_pins WHERE user_id = $1 AND world_id = $2 AND entry_id = $3
`

type DeletePinParams struct {
	UserID  pgtype.UUID
	WorldID pgtype.UUID
	EntryID pgtype.UUID
}

func (q *Queries) DeletePin(ctx context.Context, arg DeletePinParams) error {
	_, err := q.db.Exec(ctx, deletePin, arg.UserID, arg.WorldID, arg.EntryID)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, world_id, user_id, title, evicted, created_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.UserID,
		&i.Title,
		&i.Evicted,
		&i.CreatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT c.id, c.world_id, c.user_id, c.title, c.evicted, c.created_at, (SELECT count(*) FROM messages m WHERE m.conversation_id = c.id) AS message_count
FROM conversations c
WHERE c.world_id = $1 AND c.user_id = $2
ORDER BY c.created_at DESC
`

type ListConversationsParams struct {
	WorldID pgtype.UUID
	UserID  pgtype.UUID
}

type ListConversationsRow struct {
	ID           pgtype.UUID
	WorldID      pgtype.UUID
	UserID       pgtype.UUID
	Title        string
	Evicted      []byte
	CreatedAt    pgtype.Timestamptz
	MessageCount int64
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.WorldID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.UserID,
			&i.Title,
			&i.Evicted,
			&i.CreatedAt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, content, created_at FROM messages WHERE conversation_id = $1 ORDER BY created_at
`

func (q *Queries) ListMessages(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPins = `-- name: ListPins :many
SELECT p.user_id, p.world_id, p.entry_id, p.with_neighbors, p.created_at, e.title
FROM context_pins p
JOIN entries e ON e.id = p.entry_id
WHERE p.user_id = $1 AND p.world_id = $2
ORDER BY p.created_at
`

type ListPinsParams struct {
	UserID  pgtype.UUID
	WorldID pgtype.UUID
}

type ListPinsRow struct {
	UserID        pgtype.UUID
	WorldID       pgtype.UUID
	EntryID       pgtype.UUID
	WithNeighbors bool
	CreatedAt     pgtype.Timestamptz
	Title         string
}

func (q *Queries) ListPins(ctx context.Context, arg ListPinsParams) ([]ListPinsRow, error) {
	rows, err := q.db.Query(ctx, listPins, arg.UserID, arg.WorldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPinsRow
	for rows.Next() {
		var i ListPinsRow
		if err := rows.Scan(
			&i.UserID,
			&i.WorldID,
			&i.EntryID,
			&i.WithNeighbors,
			&i.CreatedAt,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationEvicted = `-- name: UpdateConversationEvicted :exec
UPDATE conversations SET evicted = $2 WHERE id = $1
`

type UpdateConversationEvictedParams struct {
	ID      pgtype.UUID
	Evicted []byte
}

func (q *Queries) UpdateConversationEvicted(ctx context.Context, arg UpdateConversationEvictedParams) error {
	_, err := q.db.Exec(ctx, updateConversationEvicted, arg.ID, arg.Evicted)
	return err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :exec
UPDATE conversations SET title = $2 WHERE id = $1 AND title = ''
`

type UpdateConversationTitleParams struct {
	ID    pgtype.UUID
	Title string
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error {
	_, err := q.db.Exec(ctx, updateConversationTitle, arg.ID, arg.Title)
	return err
}
