// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: derived.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDerived = `-- name: GetDerived :one
SELECT entry_id, card, digest, search_text, updated_at FROM entry_derived WHERE entry_id = $1
`

func (q *Queries) GetDerived(ctx context.Context, entryID pgtype.UUID) (EntryDerived, error) {
	row := q.db.QueryRow(ctx, getDerived, entryID)
	var i EntryDerived
	err := row.Scan(
		&i.EntryID,
		&i.Card,
		&i.Digest,
		&i.SearchText,
		&i.UpdatedAt,
	)
	return i, err
}

const searchLexical = `-- name: SearchLexical :many
SELECT e.id, e.title, ty.name AS type_name, e.status, d.card,
       ts_rank(to_tsvector('english', d.search_text),
               plainto_tsquery('english', $2))::float8 AS rank,
       similarity(e.title, $2)::float8 AS title_sim
FROM entries e
JOIN entry_derived d ON d.entry_id = e.id
JOIN entry_types ty ON ty.id = e.type_id
WHERE e.world_id = $1
  AND ($3::bool = false OR e.status = 'canon')
ORDER BY rank DESC, title_sim DESC
LIMIT 200
`

type SearchLexicalParams struct {
	WorldID        pgtype.UUID
	PlaintoTsquery string
	Column3        bool
}

type SearchLexicalRow struct {
	ID       pgtype.UUID
	Title    string
	TypeName string
	Status   string
	Card     string
	Rank     float64
	TitleSim float64
}

func (q *Queries) SearchLexical(ctx context.Context, arg SearchLexicalParams) ([]SearchLexicalRow, error) {
	rows, err := q.db.Query(ctx, searchLexical, arg.WorldID, arg.PlaintoTsquery, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchLexicalRow
	for rows.Next() {
		var i SearchLexicalRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TypeName,
			&i.Status,
			&i.Card,
			&i.Rank,
			&i.TitleSim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDerived = `-- name: UpsertDerived :exec
INSERT INTO entry_derived (entry_id, card, digest, search_text, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (entry_id) DO UPDATE
SET card = EXCLUDED.card, digest = EXCLUDED.digest,
    search_text = EXCLUDED.search_text, updated_at = now()
`

type UpsertDerivedParams struct {
	EntryID    pgtype.UUID
	Card       string
	Digest     string
	SearchText string
}

func (q *Queries) UpsertDerived(ctx context.Context, arg UpsertDerivedParams) error {
	_, err := q.db.Exec(ctx, upsertDerived,
		arg.EntryID,
		arg.Card,
		arg.Digest,
		arg.SearchText,
	)
	return err
}
