// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEdge = `-- name: CreateEdge :one
INSERT INTO edges (id, world_id, from_entry, field, field_id, to_entry, annotation, status, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        (SELECT COALESCE(MAX(position) + 1, 0) FROM edges
         WHERE from_entry = $3 AND field = $4))
RETURNING id, world_id, from_entry, field, to_entry, annotation, status, position, created_at, field_id
`

type CreateEdgeParams struct {
	ID         pgtype.UUID
	WorldID    pgtype.UUID
	FromEntry  pgtype.UUID
	Field      string
	FieldID    string
	ToEntry    pgtype.UUID
	Annotation string
	Status     string
}

func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) (Edge, error) {
	row := q.db.QueryRow(ctx, createEdge,
		arg.ID,
		arg.WorldID,
		arg.FromEntry,
		arg.Field,
		arg.FieldID,
		arg.ToEntry,
		arg.Annotation,
		arg.Status,
	)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.FromEntry,
		&i.Field,
		&i.ToEntry,
		&i.Annotation,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.FieldID,
	)
	return i, err
}

const deleteEdge = `-- name: DeleteEdge :exec
DELETE FROM edges WHERE id = $1
`

func (q *Queries) DeleteEdge(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEdge, id)
	return err
}

const deleteEdgesByField = `-- name: DeleteEdgesByField :exec
DELETE FROM edges WHERE from_entry = $1 AND field = $2
`

type DeleteEdgesByFieldParams struct {
	FromEntry pgtype.UUID
	Field     string
}

func (q *Queries) DeleteEdgesByField(ctx context.Context, arg DeleteEdgesByFieldParams) error {
	_, err := q.db.Exec(ctx, deleteEdgesByField, arg.FromEntry, arg.Field)
	return err
}

const getEdge = `-- name: GetEdge :one
SELECT id, world_id, from_entry, field, to_entry, annotation, status, position, created_at, field_id FROM edges WHERE id = $1
`

func (q *Queries) GetEdge(ctx context.Context, id pgtype.UUID) (Edge, error) {
	row := q.db.QueryRow(ctx, getEdge, id)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.FromEntry,
		&i.Field,
		&i.ToEntry,
		&i.Annotation,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.FieldID,
	)
	return i, err
}

const getEntriesByIDs = `-- name: GetEntriesByIDs :many
SELECT e.id, e.title, e.status, ty.name AS type_name
FROM entries e
JOIN entry_types ty ON ty.id = e.type_id
WHERE e.id = ANY($1::uuid[])
`

type GetEntriesByIDsRow struct {
	ID       pgtype.UUID
	Title    string
	Status   string
	TypeName string
}

func (q *Queries) GetEntriesByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetEntriesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getEntriesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntriesByIDsRow
	for rows.Next() {
		var i GetEntriesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.TypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgeRows = `-- name: ListEdgeRows :many
SELECT id, world_id, from_entry, field, to_entry, annotation, status, position, created_at, field_id FROM edges WHERE world_id = $1 ORDER BY from_entry, field, position
`

func (q *Queries) ListEdgeRows(ctx context.Context, worldID pgtype.UUID) ([]Edge, error) {
	rows, err := q.db.Query(ctx, listEdgeRows, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.FromEntry,
			&i.Field,
			&i.ToEntry,
			&i.Annotation,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.FieldID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesFrom = `-- name: ListEdgesFrom :many
SELECT e.id, e.world_id, e.from_entry, e.field, e.to_entry, e.annotation, e.status, e.position, e.created_at, e.field_id, t.title AS to_title, t.status AS to_entry_status,
       ty.name AS to_type_name
FROM edges e
JOIN entries t ON t.id = e.to_entry
JOIN entry_types ty ON ty.id = t.type_id
WHERE e.from_entry = $1
ORDER BY e.field, e.position
`

type ListEdgesFromRow struct {
	ID            pgtype.UUID
	WorldID       pgtype.UUID
	FromEntry     pgtype.UUID
	Field         string
	ToEntry       pgtype.UUID
	Annotation    string
	Status        string
	Position      int32
	CreatedAt     pgtype.Timestamptz
	FieldID       string
	ToTitle       string
	ToEntryStatus string
	ToTypeName    string
}

func (q *Queries) ListEdgesFrom(ctx context.Context, fromEntry pgtype.UUID) ([]ListEdgesFromRow, error) {
	rows, err := q.db.Query(ctx, listEdgesFrom, fromEntry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEdgesFromRow
	for rows.Next() {
		var i ListEdgesFromRow
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.FromEntry,
			&i.Field,
			&i.ToEntry,
			&i.Annotation,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.FieldID,
			&i.ToTitle,
			&i.ToEntryStatus,
			&i.ToTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesTo = `-- name: ListEdgesTo :many
SELECT e.id, e.world_id, e.from_entry, e.field, e.to_entry, e.annotation, e.status, e.position, e.created_at, e.field_id, f.title AS from_title, f.status AS from_entry_status,
       f.type_id AS from_type_id, ty.name AS from_type_name
FROM edges e
JOIN entries f ON f.id = e.from_entry
JOIN entry_types ty ON ty.id = f.type_id
WHERE e.to_entry = $1
ORDER BY e.field, e.position
`

type ListEdgesToRow struct {
	ID              pgtype.UUID
	WorldID         pgtype.UUID
	FromEntry       pgtype.UUID
	Field           string
	ToEntry         pgtype.UUID
	Annotation      string
	Status          string
	Position        int32
	CreatedAt       pgtype.Timestamptz
	FieldID         string
	FromTitle       string
	FromEntryStatus string
	FromTypeID      pgtype.UUID
	FromTypeName    string
}

func (q *Queries) ListEdgesTo(ctx context.Context, toEntry pgtype.UUID) ([]ListEdgesToRow, error) {
	rows, err := q.db.Query(ctx, listEdgesTo, toEntry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEdgesToRow
	for rows.Next() {
		var i ListEdgesToRow
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.FromEntry,
			&i.Field,
			&i.ToEntry,
			&i.Annotation,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.FieldID,
			&i.FromTitle,
			&i.FromEntryStatus,
			&i.FromTypeID,
			&i.FromTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesTouching = `-- name: ListEdgesTouching :many
SELECT id, world_id, from_entry, field, to_entry, annotation, status, position, created_at, field_id FROM edges
WHERE from_entry = ANY($1::uuid[]) OR to_entry = ANY($1::uuid[])
`

func (q *Queries) ListEdgesTouching(ctx context.Context, dollar_1 []pgtype.UUID) ([]Edge, error) {
	rows, err := q.db.Query(ctx, listEdgesTouching, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.FromEntry,
			&i.Field,
			&i.ToEntry,
			&i.Annotation,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.FieldID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionEdgesTo = `-- name: ListMentionEdgesTo :many
SELECT id, world_id, from_entry, field, to_entry, annotation, status, position, created_at, field_id FROM edges WHERE to_entry = $1 AND field = 'mentions'
`

func (q *Queries) ListMentionEdgesTo(ctx context.Context, toEntry pgtype.UUID) ([]Edge, error) {
	rows, err := q.db.Query(ctx, listMentionEdgesTo, toEntry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.FromEntry,
			&i.Field,
			&i.ToEntry,
			&i.Annotation,
			&i.Status,
			&i.Position,
			&i.CreatedAt,
			&i.FieldID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteEdgesFrom = `-- name: PromoteEdgesFrom :exec
UPDATE edges SET status = 'canon' WHERE from_entry = $1
`

func (q *Queries) PromoteEdgesFrom(ctx context.Context, fromEntry pgtype.UUID) error {
	_, err := q.db.Exec(ctx, promoteEdgesFrom, fromEntry)
	return err
}

const renameEdgeField = `-- name: RenameEdgeField :exec
UPDATE edges SET field = $3
WHERE field = $2
  AND from_entry IN (SELECT id FROM entries WHERE type_id = ANY($1::uuid[]))
`

type RenameEdgeFieldParams struct {
	Column1 []pgtype.UUID
	Field   string
	Field_2 string
}

func (q *Queries) RenameEdgeField(ctx context.Context, arg RenameEdgeFieldParams) error {
	_, err := q.db.Exec(ctx, renameEdgeField, arg.Column1, arg.Field, arg.Field_2)
	return err
}

const setEdgeStatus = `-- name: SetEdgeStatus :one
UPDATE edges SET status = $2 WHERE id = $1 RETURNING id, world_id, from_entry, field, to_entry, annotation, status, position, created_at, field_id
`

type SetEdgeStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) SetEdgeStatus(ctx context.Context, arg SetEdgeStatusParams) (Edge, error) {
	row := q.db.QueryRow(ctx, setEdgeStatus, arg.ID, arg.Status)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.FromEntry,
		&i.Field,
		&i.ToEntry,
		&i.Annotation,
		&i.Status,
		&i.Position,
		&i.CreatedAt,
		&i.FieldID,
	)
	return i, err
}
