// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (id, world_id, type_id, title, fields, body, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, world_id, type_id, title, fields, body, status, created_at, updated_at
`

type CreateEntryParams struct {
	ID      pgtype.UUID
	WorldID pgtype.UUID
	TypeID  pgtype.UUID
	Title   string
	Fields  []byte
	Body    []byte
	Status  string
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.ID,
		arg.WorldID,
		arg.TypeID,
		arg.Title,
		arg.Fields,
		arg.Body,
		arg.Status,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.TypeID,
		&i.Title,
		&i.Fields,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRevision = `-- name: CreateRevision :one
INSERT INTO revisions (id, entry_id, author, title, fields, body, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, entry_id, author, title, fields, body, status, created_at
`

type CreateRevisionParams struct {
	ID      pgtype.UUID
	EntryID pgtype.UUID
	Author  string
	Title   string
	Fields  []byte
	Body    []byte
	Status  string
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) (Revision, error) {
	row := q.db.QueryRow(ctx, createRevision,
		arg.ID,
		arg.EntryID,
		arg.Author,
		arg.Title,
		arg.Fields,
		arg.Body,
		arg.Status,
	)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Author,
		&i.Title,
		&i.Fields,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, world_id, type_id, title, fields, body, status, created_at, updated_at FROM entries WHERE id = $1
`

func (q *Queries) GetEntry(ctx context.Context, id pgtype.UUID) (Entry, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.TypeID,
		&i.Title,
		&i.Fields,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT id, entry_id, author, title, fields, body, status, created_at FROM revisions WHERE id = $1
`

func (q *Queries) GetRevision(ctx context.Context, id pgtype.UUID) (Revision, error) {
	row := q.db.QueryRow(ctx, getRevision, id)
	var i Revision
	err := row.Scan(
		&i.ID,
		&i.EntryID,
		&i.Author,
		&i.Title,
		&i.Fields,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT e.id, e.world_id, e.type_id, e.title, e.fields, e.body, e.status, e.created_at, e.updated_at, t.name AS type_name
FROM entries e
JOIN entry_types t ON t.id = e.type_id
WHERE e.world_id = $1
ORDER BY t.name, e.title
`

type ListEntriesRow struct {
	ID        pgtype.UUID
	WorldID   pgtype.UUID
	TypeID    pgtype.UUID
	Title     string
	Fields    []byte
	Body      []byte
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	TypeName  string
}

func (q *Queries) ListEntries(ctx context.Context, worldID pgtype.UUID) ([]ListEntriesRow, error) {
	rows, err := q.db.Query(ctx, listEntries, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.TypeID,
			&i.Title,
			&i.Fields,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryRows = `-- name: ListEntryRows :many
SELECT id, world_id, type_id, title, fields, body, status, created_at, updated_at FROM entries WHERE world_id = $1 ORDER BY created_at
`

func (q *Queries) ListEntryRows(ctx context.Context, worldID pgtype.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntryRows, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.TypeID,
			&i.Title,
			&i.Fields,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT id, entry_id, author, status, created_at
FROM revisions
WHERE entry_id = $1
ORDER BY created_at DESC
`

type ListRevisionsRow struct {
	ID        pgtype.UUID
	EntryID   pgtype.UUID
	Author    string
	Status    string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListRevisions(ctx context.Context, entryID pgtype.UUID) ([]ListRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listRevisions, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevisionsRow
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.Author,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :one
UPDATE entries
SET title = $2, fields = $3, body = $4, status = $5, updated_at = now()
WHERE id = $1
RETURNING id, world_id, type_id, title, fields, body, status, created_at, updated_at
`

type UpdateEntryParams struct {
	ID     pgtype.UUID
	Title  string
	Fields []byte
	Body   []byte
	Status string
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, updateEntry,
		arg.ID,
		arg.Title,
		arg.Fields,
		arg.Body,
		arg.Status,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.TypeID,
		&i.Title,
		&i.Fields,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
