// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meta.sql

package db

import (
	"context"
)

const pgVersion = `-- name: PgVersion :one
SELECT version()
`

func (q *Queries) PgVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, pgVersion)
	var version string
	err := row.Scan(&version)
	return version, err
}
