// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ContextPin struct {
	UserID        pgtype.UUID
	WorldID       pgtype.UUID
	EntryID       pgtype.UUID
	WithNeighbors bool
	CreatedAt     pgtype.Timestamptz
}

type Conversation struct {
	ID        pgtype.UUID
	WorldID   pgtype.UUID
	UserID    pgtype.UUID
	Title     string
	Evicted   []byte
	CreatedAt pgtype.Timestamptz
}

type Edge struct {
	ID         pgtype.UUID
	WorldID    pgtype.UUID
	FromEntry  pgtype.UUID
	Field      string
	ToEntry    pgtype.UUID
	Annotation string
	Status     string
	Position   int32
	CreatedAt  pgtype.Timestamptz
}

type Entry struct {
	ID        pgtype.UUID
	WorldID   pgtype.UUID
	TypeID    pgtype.UUID
	Title     string
	Fields    []byte
	Body      []byte
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type EntryDerived struct {
	EntryID    pgtype.UUID
	Card       string
	Digest     string
	SearchText string
	UpdatedAt  pgtype.Timestamptz
}

type EntryType struct {
	ID        pgtype.UUID
	WorldID   pgtype.UUID
	Name      string
	ParentID  pgtype.UUID
	Fields    []byte
	Builtin   bool
	CreatedAt pgtype.Timestamptz
}

type Message struct {
	ID             pgtype.UUID
	ConversationID pgtype.UUID
	Role           string
	Content        []byte
	CreatedAt      pgtype.Timestamptz
}

type Revision struct {
	ID        pgtype.UUID
	EntryID   pgtype.UUID
	Author    string
	Title     string
	Fields    []byte
	Body      []byte
	Status    string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
}

type World struct {
	ID        pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	Settings  []byte
}
