// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: worlds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntryType = `-- name: CreateEntryType :one
INSERT INTO entry_types (id, world_id, name, parent_id, fields, builtin)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, world_id, name, parent_id, fields, builtin, created_at
`

type CreateEntryTypeParams struct {
	ID       pgtype.UUID
	WorldID  pgtype.UUID
	Name     string
	ParentID pgtype.UUID
	Fields   []byte
	Builtin  bool
}

func (q *Queries) CreateEntryType(ctx context.Context, arg CreateEntryTypeParams) (EntryType, error) {
	row := q.db.QueryRow(ctx, createEntryType,
		arg.ID,
		arg.WorldID,
		arg.Name,
		arg.ParentID,
		arg.Fields,
		arg.Builtin,
	)
	var i EntryType
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Name,
		&i.ParentID,
		&i.Fields,
		&i.Builtin,
		&i.CreatedAt,
	)
	return i, err
}

const createWorld = `-- name: CreateWorld :one
INSERT INTO worlds (id, owner_id, name)
VALUES ($1, $2, $3)
RETURNING id, owner_id, name, created_at
`

type CreateWorldParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
	Name    string
}

func (q *Queries) CreateWorld(ctx context.Context, arg CreateWorldParams) (World, error) {
	row := q.db.QueryRow(ctx, createWorld, arg.ID, arg.OwnerID, arg.Name)
	var i World
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getEntryType = `-- name: GetEntryType :one
SELECT id, world_id, name, parent_id, fields, builtin, created_at FROM entry_types WHERE id = $1
`

func (q *Queries) GetEntryType(ctx context.Context, id pgtype.UUID) (EntryType, error) {
	row := q.db.QueryRow(ctx, getEntryType, id)
	var i EntryType
	err := row.Scan(
		&i.ID,
		&i.WorldID,
		&i.Name,
		&i.ParentID,
		&i.Fields,
		&i.Builtin,
		&i.CreatedAt,
	)
	return i, err
}

const getWorld = `-- name: GetWorld :one
SELECT id, owner_id, name, created_at FROM worlds WHERE id = $1
`

func (q *Queries) GetWorld(ctx context.Context, id pgtype.UUID) (World, error) {
	row := q.db.QueryRow(ctx, getWorld, id)
	var i World
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listEntryTypes = `-- name: ListEntryTypes :many
SELECT id, world_id, name, parent_id, fields, builtin, created_at FROM entry_types WHERE world_id = $1 ORDER BY builtin DESC, name
`

func (q *Queries) ListEntryTypes(ctx context.Context, worldID pgtype.UUID) ([]EntryType, error) {
	rows, err := q.db.Query(ctx, listEntryTypes, worldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryType
	for rows.Next() {
		var i EntryType
		if err := rows.Scan(
			&i.ID,
			&i.WorldID,
			&i.Name,
			&i.ParentID,
			&i.Fields,
			&i.Builtin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorlds = `-- name: ListWorlds :many
SELECT id, owner_id, name, created_at FROM worlds WHERE owner_id = $1 ORDER BY created_at
`

func (q *Queries) ListWorlds(ctx context.Context, ownerID pgtype.UUID) ([]World, error) {
	rows, err := q.db.Query(ctx, listWorlds, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []World
	for rows.Next() {
		var i World
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
