// GENERATED by cmd/gentools from internal/tools structs — do not edit.
// Regenerate: make tools-docs
import type { DocMark, DocNode } from "./doc";
export type { DocMark, DocNode };

export interface CanonScope {
  fields: string[] | null;
  body: boolean;
  edges: boolean;
}

export interface Edge {
  id: string;
  field: string;
  field_id?: string;
  to: EntryRef;
  annotation?: string;
  status: string;
  incoming?: boolean;
}

export interface EdgeDump {
  from_entry: string;
  field: string;
  field_id?: string;
  to_entry: string;
  annotation?: string;
  status: string;
}

export interface Entry {
  id: string;
  world_id: string;
  type_id: string;
  type_name: string;
  title: string;
  fields: Record<string, FieldValue>;
  body_md: string;
  body_doc: DocNode;
  status: string;
  updated_at: string;
  relations: RelationSection[] | null;
}

export interface EntryDump {
  id: string;
  type_id: string;
  title: string;
  fields: unknown;
  body: unknown;
  status: string;
}

export interface EntryRef {
  id: string;
  title: string;
  type_name: string;
  status: string;
}

export interface EntrySummary {
  id: string;
  title: string;
  type_id: string;
  type_name: string;
  status: string;
}

export interface EntryType {
  id: string;
  name: string;
  parent_id?: string;
  fields: FieldDef[] | null;
  builtin: boolean;
}

export interface FieldDef {
  id?: string;
  name: string;
  kind: string;
  label?: string;
  relation?: RelationConfig;
}

export interface FieldValue {
  value: unknown;
  value_doc?: unknown;
  status: string;
}

export interface Graph {
  nodes: GraphNode[] | null;
  edges: GraphEdge[] | null;
}

export interface GraphEdge {
  id: string;
  from: string;
  to: string;
  field: string;
  annotation?: string;
  status: string;
}

export interface GraphNode {
  id: string;
  title: string;
  type_name: string;
  status: string;
  depth: number;
}

export interface RelationConfig {
  targets?: string[] | null;
  many?: boolean;
  inverse_label?: string;
  annotations?: boolean;
}

export interface RelationSection {
  field: string;
  field_id?: string;
  label: string;
  reverse?: boolean;
  config?: RelationConfig;
  edges: Edge[] | null;
}

export interface Revision {
  id: string;
  author: string;
  status: string;
  created_at: string;
}

export interface RevisionDetail {
  id: string;
  author: string;
  status: string;
  created_at: string;
  title: string;
  fields: Record<string, FieldValue>;
  body_md: string;
}

export interface SearchResult {
  id: string;
  title: string;
  type_name: string;
  status: string;
  card: string;
  score: number;
}

export interface Tray {
  items: TrayItem[] | null;
  total_tokens: number;
  budget: number;
}

export interface TrayItem {
  entry_id: string;
  title: string;
  source: string;
  level: string;
  text: string;
  tokens: number;
  neighbors?: boolean;
  score?: number;
}

export interface TypeDump {
  id: string;
  name: string;
  parent_id?: string;
  fields: unknown;
  builtin: boolean;
}

export interface World {
  id: string;
  name: string;
  settings: WorldSettings;
  created_at: string;
}

export interface WorldDump {
  version: number;
  world: string;
  types: TypeDump[] | null;
  entries: EntryDump[] | null;
  edges: EdgeDump[] | null;
}

export interface WorldSettings {
  vibe?: string;
  style_prompt?: string;
  humans_author_as?: string;
  ai_can_edit_canon?: boolean;
}

